list = [0, 1, 2, 3, 4,]
dict = {'a': 1, 'b': 2, 'c': 3,}

list[10]
# IndexError: List index out of range

dict['d']
# Traceback(most recent call last):

# A NameError arises when a name is referenced before it has been defined.

#  flatiron_school
# Traceback (most recent call last):
# ", line 1, in <module>
# NameError: name 'flatiron_school' is not defined